'use client';
import { useEffect,useMemo,useState } from 'react';
import { calculateAll,loadRecommendationData,subscribeWeather,type Input,type PriorityId,type Result,type Weather } from './recommendation-store';
const priorities:PriorityId[]=['safety','lowCrowd','scenery','parking','publicTransport','calmWave','lowRain','lowUV','facilities'];
const labels:Record<PriorityId,string>={safety:'안전',lowCrowd:'한적함',scenery:'경치',parking:'주차',publicTransport:'대중교통',calmWave:'잔잔한 파도',lowRain:'낮은 강수',lowUV:'낮은 자외선',facilities:'편의시설'};
export default function Home(){const [data,setData]=useState<Awaited<ReturnType<typeof loadRecommendationData>>|null>(null),[error,setError]=useState<string|null>(null),[input,setInput]=useState<Input>({activityId:'walking',priorities:[]}),[selectedId,setSelectedId]=useState<string|null>(null);
useEffect(()=>{let stop=()=>{};loadRecommendationData().then(d=>{setData(d);stop=subscribeWeather((weather:Weather[])=>setData(current=>current&&weather.length?{...current,weather}:current),e=>setError(e.message));}).catch(e=>setError(e instanceof Error?e.message:'Firestore 데이터를 불러오지 못했습니다.'));return()=>stop();},[]);
const results=useMemo(()=>data?calculateAll(data,input):[],[data,input]);const byId=useMemo(()=>new Map(results.map(r=>[r.beachId,r])),[results]);const selected=selectedId?byId.get(selectedId):results[0];const beach=selected&&data?.beaches.find(x=>x.id===selected.beachId);const toggle=(p:PriorityId)=>setInput(v=>({...v,priorities:v.priorities.includes(p)?v.priorities.filter(x=>x!==p):[...v.priorities,p]}));
if(error)return <main className="section"><h1>추천 데이터를 불러오지 못했습니다.</h1><p>{error}</p><p>Firestore 연결과 읽기 권한을 확인한 뒤 다시 시도해 주세요.</p></main>;if(!data)return <main className="section"><h1>추천 데이터를 불러오는 중입니다…</h1><p>Firestore의 해변·날씨·가중치 데이터를 준비하고 있습니다.</p></main>;
return <main><header className="nav"><b>오늘바다 부산</b><span>Firestore Live Recommendation</span></header><section className="hero"><p>EXPLAINABLE AI · LIVE DATA</p><h1>오늘, 어디로 갈까요?</h1><p>모든 점수는 Firestore에서 불러온 동일한 RecommendationResult로 표시됩니다.</p></section><section className="section"><h2>무엇을 하고 싶나요?</h2><div className="activity-grid">{['walking','swimming','family','surfing','photo','sunset','relaxation','petWalking'].map(id=><button key={id} className={input.activityId===id?'chosen':''} onClick={()=>setInput(v=>({...v,activityId:id}))}>{id}</button>)}</div><h2>우선순위</h2><div className="activity-grid">{priorities.map(p=><button key={p} className={input.priorities.includes(p)?'chosen':''} onClick={()=>toggle(p)}>{labels[p]}</button>)}</div></section><section className="section"><h2>오늘의 AI 추천</h2><div className="recommend-result">{results.slice(0,1).map(r=><><p>추천 1위</p><h3>{data.beaches.find(b=>b.id===r.beachId)?.name}</h3><strong>{r.totalScore}<small>점</small></strong>{r.reasons.map(x=><p key={x}>• {x}</p>)}</>)}</div></section><section className="section map-section"><h2>지도 · 추천 카드 · AI 분석</h2><div className="map-layout"><div className="map">{data.beaches.map((b,i)=>{const r=byId.get(b.id)!;return <button key={b.id} className={'pin '+(selected?.beachId===b.id?'selected':'')} style={{left:`${15+(i%4)*23}%`,top:`${20+Math.floor(i/4)*45}%`}} onClick={()=>setSelectedId(b.id)}><span>{r.totalScore}</span><small>{b.name}</small></button>})}</div>{selected&&beach&&<aside className="beach-detail"><p>선택한 해변</p><h3>{beach.name}</h3><div className="score"><strong>{selected.totalScore}</strong><span>점<br/><small>{selected.grade}</small></span></div><h4>AI 분석</h4>{selected.breakdown.map(x=><p key={x.criterionId}>{x.criterionId}: {x.score}점 · {(x.weight*100).toFixed(1)}% · 기여 {x.contribution.toFixed(1)}</p>)}<h4>추천 이유</h4>{selected.reasons.map(x=><p key={x}>• {x}</p>)}</aside>}</div></section></main>}
