"use client";

import { useMemo, useState } from "react";
import { PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer } from "recharts";

type Activity = "swimming" | "family" | "walking" | "surfing" | "photo" | "sunset" | "relaxation" | "petWalking";
type Criterion = "weatherSuitability" | "marineSuitability" | "safety" | "activitySuitability" | "comfort" | "scenery" | "accessibility";
type Beach = { id: string; name: string; temp: number; wave: number; wind: number; rain: number; x: number; y: number; activity: Record<Activity, number>; base: Record<Exclude<Criterion, "weatherSuitability" | "marineSuitability" | "activitySuitability">, number>; note: string };

const activities: Record<Activity, string> = { swimming: "수영·물놀이", family: "가족 나들이", walking: "산책", surfing: "서핑", photo: "사진 촬영", sunset: "노을 감상", relaxation: "힐링·휴식", petWalking: "반려동물 산책" };
const labels: Record<Criterion, string> = { weatherSuitability: "기상 적합성", marineSuitability: "해양환경 적합성", safety: "안전성", activitySuitability: "활동 적합성", comfort: "쾌적성", scenery: "경관성", accessibility: "접근·편의성" };
const criteria: Criterion[] = ["weatherSuitability", "marineSuitability", "safety", "activitySuitability", "comfort", "scenery", "accessibility"];
const weights: Record<Activity, Record<Criterion, number>> = {
  swimming: { weatherSuitability: .15, marineSuitability: .30, safety: .25, activitySuitability: .15, comfort: .05, scenery: .05, accessibility: .05 },
  family: { weatherSuitability: .10, marineSuitability: .15, safety: .25, activitySuitability: .10, comfort: .15, scenery: .05, accessibility: .20 },
  walking: { weatherSuitability: .25, marineSuitability: .05, safety: .10, activitySuitability: .15, comfort: .20, scenery: .15, accessibility: .10 },
  surfing: { weatherSuitability: .10, marineSuitability: .35, safety: .20, activitySuitability: .20, comfort: .05, scenery: .05, accessibility: .05 },
  photo: { weatherSuitability: .15, marineSuitability: .05, safety: .05, activitySuitability: .15, comfort: .10, scenery: .40, accessibility: .10 },
  sunset: { weatherSuitability: .15, marineSuitability: .05, safety: .05, activitySuitability: .15, comfort: .10, scenery: .40, accessibility: .10 },
  relaxation: { weatherSuitability: .15, marineSuitability: .05, safety: .05, activitySuitability: .10, comfort: .30, scenery: .25, accessibility: .10 },
  petWalking: { weatherSuitability: .20, marineSuitability: .05, safety: .10, activitySuitability: .15, comfort: .25, scenery: .10, accessibility: .15 },
};
const beaches: Beach[] = [
  { id: "hae", name: "해운대해수욕장", temp: 27, wave: .4, wind: 2.1, rain: 8, x: 79, y: 24, activity: { swimming: 88, family: 89, walking: 83, surfing: 73, photo: 91, sunset: 85, relaxation: 78, petWalking: 60 }, base: { safety: 90, comfort: 62, scenery: 93, accessibility: 96 }, note: "넓은 백사장과 풍부한 편의시설이 강점입니다." },
  { id: "gwang", name: "광안리해수욕장", temp: 27, wave: .3, wind: 1.8, rain: 5, x: 64, y: 28, activity: { swimming: 85, family: 84, walking: 93, surfing: 68, photo: 94, sunset: 96, relaxation: 84, petWalking: 72 }, base: { safety: 92, comfort: 76, scenery: 97, accessibility: 91 }, note: "광안대교가 어우러진 야경과 산책 풍경이 좋습니다." },
  { id: "song", name: "송정해수욕장", temp: 26, wave: .6, wind: 3.4, rain: 12, x: 90, y: 13, activity: { swimming: 82, family: 75, walking: 86, surfing: 96, photo: 82, sunset: 81, relaxation: 82, petWalking: 84 }, base: { safety: 82, comfort: 86, scenery: 85, accessibility: 76 }, note: "서핑과 한적한 산책을 즐기기 좋은 해변입니다." },
  { id: "dadae", name: "다대포해수욕장", temp: 26, wave: .5, wind: 3.2, rain: 15, x: 10, y: 90, activity: { swimming: 78, family: 79, walking: 91, surfing: 82, photo: 88, sunset: 97, relaxation: 92, petWalking: 86 }, base: { safety: 86, comfort: 91, scenery: 94, accessibility: 75 }, note: "넓은 모래사장과 노을을 여유롭게 즐길 수 있습니다." },
  { id: "songdo", name: "송도해수욕장", temp: 25, wave: .7, wind: 4.1, rain: 18, x: 29, y: 73, activity: { swimming: 70, family: 76, walking: 80, surfing: 77, photo: 89, sunset: 82, relaxation: 76, petWalking: 66 }, base: { safety: 76, comfort: 72, scenery: 90, accessibility: 88 }, note: "도심에서 가까운 해안 산책 코스가 있습니다." },
  { id: "ilgw", name: "일광해수욕장", temp: 26, wave: .5, wind: 2.8, rain: 10, x: 84, y: 8, activity: { swimming: 84, family: 85, walking: 89, surfing: 78, photo: 86, sunset: 88, relaxation: 90, petWalking: 87 }, base: { safety: 89, comfort: 91, scenery: 88, accessibility: 72 }, note: "한적한 분위기에서 산책과 휴식을 즐기기 좋은 해변입니다." },
  { id: "imn", name: "임랑해수욕장", temp: 26, wave: .6, wind: 3.0, rain: 11, x: 92, y: 4, activity: { swimming: 80, family: 78, walking: 85, surfing: 82, photo: 83, sunset: 86, relaxation: 84, petWalking: 88 }, base: { safety: 84, comfort: 87, scenery: 86, accessibility: 68 }, note: "조용한 해안 풍경과 반려동물 산책에 어울리는 해변입니다." },
];

function scores(beach: Beach, activity: Activity): Record<Criterion, number> {
  return { weatherSuitability: Math.max(45, Math.min(100, 100 - beach.rain - Math.max(0, beach.temp - 29) * 3)), marineSuitability: Math.max(35, Math.round(100 - beach.wave * 25 - Math.max(0, beach.wind - 3) * 5)), safety: beach.base.safety, activitySuitability: beach.activity[activity], comfort: beach.base.comfort, scenery: beach.base.scenery, accessibility: beach.base.accessibility };
}
function result(beach: Beach, activity: Activity) {
  const values = scores(beach, activity); const raw = criteria.reduce((sum, key) => sum + values[key] * weights[activity][key], 0);
  const restricted = activity === "swimming" && (beach.wave >= 1 || beach.wind >= 10 || values.safety < 60);
  return { values, restricted, total: restricted ? Math.min(59, Math.round(raw)) : Math.round(raw) };
}
function details(key: Criterion, beach: Beach) { const map: Record<Criterion, string> = { weatherSuitability: `기온 ${beach.temp}℃ - 강수확률 ${beach.rain}% - 기상청 Open API`, marineSuitability: `파고 ${beach.wave}m - 풍속 ${beach.wind}m/s - 시연용 해양 데이터`, safety: "파도 위험 낮음 - 강풍 없음 - 안전시설 운영 정보", activitySuitability: "선택 활동 - 해변 고유 특성 적합도", comfort: "혼잡도 - 소음 - 대기질 - 체감환경", scenery: "경관 기본점수 - 가시거리 - 일몰 조건", accessibility: "대중교통 - 주차 - 화장실 - 편의시설" }; return map[key]; }

function Analysis({ beach, activity, close }: { beach: Beach; activity: Activity; close: () => void }) {
  const data = result(beach, activity); const chart = criteria.map((key) => ({ subject: labels[key], value: data.values[key] }));
  return <div className="modal-backdrop analysis-backdrop"><section className="analysis-modal"><button className="close" onClick={close}>×</button><header className="analysis-head"><div><p className="kicker">EXPLAINABLE AI · ANALYSIS</p><h2>{beach.name} 추천 분석</h2><p>{activities[activity]} · 동일한 7개 평가기준 적용</p></div><div className="grade"><strong>{data.total}</strong><span>/100</span><small>★★★★★<b>{data.restricted ? "안전 제한" : "매우 추천"}</b></small></div></header><div className="analysis-grid"><section className="radar-card"><h3>7개 평가기준 점수</h3><div className="radar"><ResponsiveContainer width="100%" height="100%"><RadarChart data={chart}><PolarGrid/><PolarAngleAxis dataKey="subject"/><Radar dataKey="value" stroke="#1687a6" fill="#40c2bb" fillOpacity={.45}/></RadarChart></ResponsiveContainer></div></section><section className="reason-card"><p className="kicker">WHY THIS BEACH</p><h3>추천 이유</h3><p className="narrative">“{beach.wave}m의 파고와 {beach.wind}m/s의 풍속, {beach.rain}%의 강수확률을 종합해 {activities[activity]}에 적합한지 계산했습니다.”</p>{data.restricted && <div className="not-recommend"><b>안전 제한이 적용되었습니다</b><p>위험 기준을 초과하면 높은 점수라도 수영·물놀이를 추천하지 않습니다.</p></div>}</section></div><section className="calculation"><h3>평가기준 및 점수 계산</h3><div className="calc-table"><span>동일한 7개 기준</span><span>기준 점수 × 가중치</span><span>기여점수</span>{criteria.map((key) => <><b key={`${key}-name`}>{labels[key]}<small>{details(key, beach)}</small></b><b key={`${key}-weight`}>{data.values[key]} × {(weights[activity][key] * 100).toFixed(0)}%</b><strong key={`${key}-score`}>{(data.values[key] * weights[activity][key]).toFixed(1)}점</strong></>)}<b className="total">총점</b><span className="total">가중치 합계 100%</span><strong className="total">{data.total}점</strong></div></section><p className="algorithm">기상·해양 데이터는 최신 수집값을 기반으로 하며, 동일 조건에서는 항상 같은 규칙 기반 Explainable AI 결과가 나옵니다.</p></section></div>;
}

export default function Home() {
  const [activity, setActivity] = useState<Activity>("walking"); const [selected, setSelected] = useState(beaches[1]); const [analysis, setAnalysis] = useState(false);
  const ranked = useMemo(() => [...beaches].sort((a, b) => result(b, activity).total - result(a, activity).total), [activity]); const best = ranked[0];
  return <main><header className="nav"><a className="brand" href="#top"><span>⌁</span>오늘바다 <small>BUSAN</small></a><nav><a href="#map">추천지도</a><a href="#recommend">맞춤추천</a></nav></header><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">LIVE DATA · BUSAN</p><h1>오늘, 당신에게 가장<br/><em>좋은 바다는 어디인가요?</em></h1><p>7개 통일 기준과 이용 목적별 가중치로 추천합니다.</p><button className="primary" onClick={() => document.getElementById("recommend")?.scrollIntoView({ behavior: "smooth" })}>맞춤 추천 받기 →</button></div><div className="hero-orb"><div className="sun"/><div className="hero-stat"><span>부산 오늘의 추천</span><b>{result(best, activity).total}</b><p>{activities[activity]}에 맞춘 설명 가능한 추천</p></div></div></section><section className="section" id="recommend"><div className="section-head"><div><p className="kicker">PERSONAL PICK</p><h2>나의 목적에 맞는 바다</h2><p>목적에 따라 가중치만 달라지고, 평가 기준은 항상 같은 7개입니다.</p></div></div><div className="activity-grid purpose-grid">{(Object.keys(activities) as Activity[]).map((key) => <button key={key} className={activity === key ? "chosen" : ""} onClick={() => setActivity(key)}><span>◌</span>{activities[key]}<small>{activity === key ? "선택됨" : "선택"}</small></button>)}</div><div className="recommend-result"><p>당신을 위한 첫 번째 선택</p><div className="result-name"><span>01</span><h3>{best.name}</h3></div><strong>{result(best, activity).total}<small>점</small></strong><div className="reasons"><p>✓ {labels.activitySuitability} {scores(best, activity).activitySuitability}점</p><p>✓ {labels.safety} {scores(best, activity).safety}점</p><p>✓ {best.note}</p></div><button onClick={() => { setSelected(best); document.getElementById("map")?.scrollIntoView({ behavior: "smooth" }); }}>Beach Finder에서 위치 보기 →</button></div></section><section className="section map-section" id="map"><div className="section-head"><div><p className="kicker">BEACH FINDER</p><h2>추천 해변 비교</h2></div></div><div className="map-layout"><div className="map">{ranked.map((beach) => <button key={beach.id} className={`pin ${selected.id === beach.id ? "selected" : ""}`} style={{ left: `${beach.x}%`, top: `${beach.y}%` }} onClick={() => setSelected(beach)}><span>{result(beach, activity).total}</span><small>{beach.name.replace("해수욕장", "")}</small></button>)}</div><aside className="beach-detail"><p>선택한 해변</p><h3>{selected.name}</h3><div className="score"><strong>{result(selected, activity).total}</strong><span>점<br/><small>추천</small></span></div><p className="detail-note">{selected.note}</p><div className="metrics"><span>🌡️ <b>{selected.temp}°</b>기온</span><span>≋ <b>{selected.wave}m</b>파고</span><span>↝ <b>{selected.wind}m/s</b>바람</span></div><button className="ai-button" onClick={() => setAnalysis(true)}>✦ AI 분석 보기</button></aside></div></section>{analysis && <Analysis beach={selected} activity={activity} close={() => setAnalysis(false)}/>}</main>;
}
