import { collection, getDocs, onSnapshot, type Unsubscribe } from 'firebase/firestore';
import { db } from './firebase';
export type CriterionId='weatherSuitability'|'marineSuitability'|'safety'|'activitySuitability'|'comfort'|'scenery'|'accessibility';
export type PriorityId='safety'|'lowCrowd'|'scenery'|'parking'|'publicTransport'|'calmWave'|'lowRain'|'lowUV'|'facilities';
export type Beach={id:string;name:string;latitude:number;longitude:number;activityScores:Record<string,number>;criterionScores:Partial<Record<CriterionId,number>>;};
export type Weather={beachId:string;nameKo?:string;temperature:number;feelsLike?:number;precipitationProbability?:number|null;precipitation?:number;windSpeed:number;windDirection?:number;humidity?:number;waveHeight?:number;waterTemperature?:number;marineSource?:string;source:string;observedAt?:{toMillis:()=>number};uvIndex?:number;crowdLevel?:number;};
export type Weight={activityId:string;weights:Record<CriterionId,number>}; export type Criteria={id:CriterionId;label:string};
export type Input={activityId:string;priorities:PriorityId[];}; export type Result={beachId:string;totalScore:number;grade:'green'|'yellow'|'red';breakdown:{criterionId:CriterionId;score:number;weight:number;contribution:number}[];reasons:string[]};
const read=<T>(name:string)=>getDocs(collection(db,name)).then(s=>s.docs.map(d=>({id:d.id,...d.data()} as T)));
function latestPerBeach(records:Weather[]){return Object.values(records.reduce<Record<string,Weather>>((latest,record)=>{const previous=latest[record.beachId];const at=record.observedAt?.toMillis?.()??0;const previousAt=previous?.observedAt?.toMillis?.()??0;if(!previous||at>previousAt)latest[record.beachId]=record;return latest;},{}));}
export async function loadRecommendationData(){const [beaches,latest,history,weights,criteria,adjustments]=await Promise.all([read<Beach>('beaches'),read<Weather>('weather_latest'),read<Weather>('weather_history'),read<Weight>('activity_weights'),read<Criteria>('evaluation_criteria'),read<{priorityId:PriorityId;adjustments:Partial<Record<CriterionId,number>>}>('priority_adjustments')]);const weather=latest.length?latest:latestPerBeach(history);return {beaches,weather,weights,criteria,adjustments};}
export function subscribeWeather(onChange:(weather:Weather[])=>void,onError:(error:Error)=>void):Unsubscribe {
  return onSnapshot(
    collection(db,'weather_latest'),
    snapshot => onChange(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Weather))),
    onError,
  );
}
const ids:CriterionId[]=['weatherSuitability','marineSuitability','safety','activitySuitability','comfort','scenery','accessibility'];
export function calculateAll(data:Awaited<ReturnType<typeof loadRecommendationData>>,input:Input):Result[]{const base=data.weights.find(x=>x.activityId===input.activityId);if(!base) throw new Error(`Missing Firestore weights for ${input.activityId}`);const adjustment=data.adjustments.filter(x=>input.priorities.includes(x.priorityId));return data.beaches.map(beach=>{const weather=data.weather.find(x=>x.beachId===beach.id);if(!weather) throw new Error(`Missing latest weather for ${beach.id}`);const w={...base.weights};adjustment.forEach(a=>Object.entries(a.adjustments).forEach(([k,v])=>w[k as CriterionId]+=(v??0)));const totalWeight=ids.reduce((s,k)=>s+w[k],0);const rain=weather.precipitationProbability??(weather.precipitation&&weather.precipitation>0?100:0),wave=weather.waveHeight??0,uv=weather.uvIndex??0,crowd=weather.crowdLevel??2;const score:Record<CriterionId,number>={weatherSuitability:Math.max(0,100-rain-uv*3),marineSuitability:Math.max(0,100-wave*35-weather.windSpeed*4),safety:beach.criterionScores.safety??70,activitySuitability:beach.activityScores[input.activityId]??0,comfort:Math.max(0,100-crowd*18),scenery:beach.criterionScores.scenery??70,accessibility:beach.criterionScores.accessibility??70};const breakdown=ids.map(criterionId=>({criterionId,score:Math.round(score[criterionId]),weight:w[criterionId]/totalWeight,contribution:score[criterionId]*w[criterionId]/totalWeight}));const totalScore=Math.round(breakdown.reduce((s,x)=>s+x.contribution,0));const unsafe=wave>=1||weather.windSpeed>=10;return {beachId:beach.id,totalScore:unsafe?Math.min(59,totalScore):totalScore,grade:totalScore>=80?'green':totalScore>=65?'yellow':'red',breakdown,reasons:[weather.source.includes('KMA')?'기상청 최신 관측값을 반영했습니다.':'최신 Firestore 관측값을 반영했습니다.',wave<.5?`파고 ${wave}m로 안정적인 해양 조건입니다.`:`파고 ${wave}m를 고려해 활동을 선택하세요.`,weather.windSpeed<3?'풍속이 약해 야외 활동이 편안합니다.':`풍속 ${weather.windSpeed}m로 바람 영향을 고려했습니다.`]};}).sort((a,b)=>b.totalScore-a.totalScore);}
